# Generated by Django 4.1.7 on 2023-03-22 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aapp1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='Description',
            field=models.TextField(default='no description'),
        ),
    ]
