# Generated by Django 2.2.4 on 2023-03-28 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_travel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='trip',
            field=models.ManyToManyField(related_name='users', to='myapp.User'),
        ),
    ]
