# Generated by Django 2.2.4 on 2023-03-28 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20230328_0521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travel',
            name='trip',
        ),
        migrations.AddField(
            model_name='travel',
            name='user',
            field=models.ManyToManyField(related_name='travels', to='myapp.User'),
        ),
    ]
